### ISSUE TITLE
zeigt nicht alle ziele auf der Karte an

### ISSUE THREAD

**Issue by nethzt** [finderlein/noefinderlein_flutter#3]
leider ist die karte heute sehr unvollständig, obwohl kein Filter gesetzt ist
![karte](https://user-images.githubusercontent.com/6165692/184627386-ec251abc-b324-42d3-82af-b868e7aab85d.jpg)

**Comment by derqurps** [comment]
Hallo, 

Das war leider ein Daten Problem. Ich wurde heute drauf hingewiesen das die Ziele schon da sind, aber in Afrika angezeigt wurden.

Die Daten sollten jetzt bereinigt sein.
Dh.: Nach einem Neustart und Update der Daten, sollten die Ziele alle auf der Karte am richtigen Ort sichtbar sein.
