### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [finderlein/noefinderlein_flutter#4]
So I;ve updated the recipe to pick Flutter version from you source code _(hope you keep that up to date and not using `^` but always exact version :stuck_out_tongue:)_: https://gitlab.com/fdroid/fdroiddata/-/commit/6176ebbbb23eb7bb9de6821960bf491b779a7110

But the CI fails: https://gitlab.com/fdroid/fdroiddata/-/jobs/4454120443#L565

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/28fa2f5be82b8e4bf5ed77681caae1f4a3579a6a

**Comment by linsui** [comment]
Fixed. https://gitlab.com/linsui/fdroiddata/-/jobs/7947400367
